<h3>Menu de Navegação</h3>
<div id="navegacao">
<ul>
<li><a href="principal.php" title="Clique aqui para voltar para a pagina principal!">Principal</a></li>
<li><a href="cadastra_contribuinte.php" title="Clique aqui para cadastrar um contribuinte!">Cadastra Contribuinte</a></li>
<li><a href="cadastra_contribuicao.php" title="Clique aqui para cadastrar uma contribuição!">Cadastra Contribuição</a></li>
<li><a href="consulta.php" title="Clique aqui para consultar contribuintes!">Consulta</a></li>
<li><a href="consulta_contribuicao.php" title="Clique aqui para consultar contribuintes!">Consulta Contribuição</a></li>
</ul>
</div>
<br>
<div id="navegacao">
<ul>
<li><a href="consulta_historico_contribuicao.php" title="Clique aqui para consultar historico de contribuições!">Histórico de Contribuições</a></li>
<li><a href="consulta_contribuinte_dia.php" title="Clique aqui para consultar contribuintes por dia!">Contribuintes por Dia</a></li>
<li><a href="consulta_contribuinte_periodo.php" title="Clique aqui para consultar contribuintes por período!">Contribuintes por Período</a></li>
<li><a href="consulta_contribuinte_anual.php" title="Clique aqui para consultar contribuintes por ano!">Contribuintes por Ano</a></li>
</ul>
</div>
<br>
<div id="navegacao">
<ul>
<li><a href="consulta_valor_dia.php" title="Clique aqui para consultar valor por dia!">Valores por Dia</a></li>
<li><a href="consulta_valor_periodo.php" title="Clique aqui para consultar valor por período!">Valores por Período</a></li>
<li><a href="consulta_valor_anual.php" title="Clique aqui para consultar valor por ano!">Valores por Ano</a></li>
</ul>
</div>
<br>
<br>
