  <tr>
    <td height="23">
        <table border="0" cellpadding="1" cellspacing="1" bgcolor="996600" width="100%">
               <tr>
                   <td bgcolor="#000000" class="titulo_tabela"><b>Menu</b></td>
                   <td width="94" height="23" bgcolor="#000000" style="cursor:hand;text-align:center;font-size:14;font-family:Verdana;" onMouseOver="javascript:this.style.backgroundColor='#C0B085'" onMouseOut="javascript:this.style.backgroundColor=''"><a href="principal.php">Início</a></td>
                   <td width="94" bgcolor="#000000" style="cursor:hand;text-align:center;font-size:14;font-family:Verdana;" onMouseOver="javascript:this.style.backgroundColor='#C0B085'" onMouseOut="javascript:this.style.backgroundColor=''"><a href="cadastro.php">Cadastro</a></td>
                   <td width="94" bgcolor="#000000" style="cursor:hand;text-align:center;font-size:14;font-family:Verdana;" onMouseOver="javascript:this.style.backgroundColor='#C0B085'" onMouseOut="javascript:this.style.backgroundColor=''"><a href="alterar.php">Alterar</a></td>
                   <td width="94" bgcolor="#000000" style="cursor:hand;text-align:center;font-size:14;font-family:Verdana;" onMouseOver="javascript:this.style.backgroundColor='#C0B085'" onMouseOut="javascript:this.style.backgroundColor=''"><a href="consulta.php">Consulta</a></td>
                   <td width="94" bgcolor="#000000" style="cursor:hand;text-align:center;font-size:14;font-family:Verdana;" onMouseOver="javascript:this.style.backgroundColor='#C0B085'" onMouseOut="javascript:this.style.backgroundColor=''"><a href="relatorio.php">Relatório</a></td>
                   <td width="94" bgcolor="#000000" style="cursor:hand;text-align:center;font-size:14;font-family:Verdana;" onMouseOver="javascript:this.style.backgroundColor='#C0B085'" onMouseOut="javascript:this.style.backgroundColor=''"><a href="javascript:window.close()">Fechar</a></td>
               </tr>
        </table>
    </td>
  </tr>
