<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>SISTEMA DE CAIXA</title>
<link rel="stylesheet" href="estilo.css" type="text/css">
<script language="JavaScript" src="js/funcao_mascara.js" type="text/javascript"></script>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body onLoad="Mascaras.carregar();">
<table width="751" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td height="78" bordercolor="#CCCCCC"><img src="img/logotipo_paroquia.gif" width="750" height="78"></td>
  </tr>
</table>
